project:
  type: website

toc: true

format:
  html:
    theme: sandstone
    css: styles.css
    page-layout: full
    linkcolor: goldenrod

website:
  favicon: "berque_crop.png"
  title: "Berque Fund"
  google-analytics: "G-9PZD005WZV"
  description: "Supporting the Berque Fund for Computer Science Scholarships"
  navbar:
    logo: "berque_crop.png"
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd
      - text: "Donate"
        href: https://docs.google.com/forms/d/1I9WnVBsZNq8AIKP5NwdT17g4cD0Ba23mgQg3KGgXKKA/edit
  body-footer: "© 2024 Berque Fund. All rights reserved"


