---
title: "Welcome to the Berque Fund"
include-in-header:
  text: '<script src="https://d3js.org/d3.v4.min.js"></script> <script src="https://davidbanksnz.github.io/d3-thermometer/thermometer.min.js"></script>'

---

Welcome to the Dave Berque Fund website. This fund supports scholarships for Computer Science students in honor of Dave Berque.


::: {.callout-important}
Eventually this site will track "soft" commitments for funds.  However, for now we're asking folks to send in:

* Pictures of Dave Berque (older the better)
* Stories about Dave Berque
* Other ideas for improvement.


The main goal here is to reach $150K.  We had a number of people mention
interest during a related meeting, but now's the time to get a little more
formal with our estimate and commitments.  We'll use this page to keep track of
the progress of planning, and also the donation commitments that we've
received.  It's great to do some for Dave after all these years.  Cheers to
everyone involved.

Send thoughts to Nate Moch or Justin Donaldson.  Regards!


:::

::: {.grid}

::: {.g-col-2}
::: {#container}
:::
:::
::: {.g-col-1}
:::


::: {.g-col-9}


* Create a Scholarship Fund: We will start by creating a scholarship fund through DePauw.
* Seed the Fund: Our target is to raise approximately $150,000 with pledges over the next 12 months. Donations can be made this year and/or next year.
* Utilize company matching programs to maximize contributions.
* Multi-year gift pledges are not feasible at this stage, as we need to complete this within the first year.
* Future Possibilities:
  * Broader Outreach: Once we have pledges from our group, we will reach out to other alumni through broader email campaigns and targeted 1:1s.
  * Potential Expansion: Depending on the success of our initial fundraising, we may consider setting a higher target (e.g., a $2 million endowed chair).
  This would involve more support from DePauw and coordination with their larger capital campaign.
  At this point, larger, multi-year pledges can be discussed.


:::


:::



```{=html}
<script>
  var thermometer = new Thermometer({
    mercuryColor: "rgb(220, 180, 0)",
    width: 100,
    height: 300,
    bulbRadius: 20,
    tubeWidth: 30,
    borderWidth: 3,
  });



	var container = document.getElementById('container');
	thermometer.render(container, 15, 15, 150);
</script>
```



